name: Test built package

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: cache poetry install
      uses: actions/cache@v2
      with:
        path: ~/.local
        key: poetry-1.8.2
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
      with:
        version: 1.8.2
    - name: cache deps
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: dependencies-${{ hashFiles('**/poetry.lock') }}

    - name: Build a binary wheel and a source tarball
      run: poetry build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/